name: Windows Build Meson

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install Python Dependencies
        run: |
          pip install meson ninja
          vcpkg install glfw3

      - name: Download sources
        shell: cmd
        run: |
          git clone --recursive https://github.com/haasn/libplacebo

      - name: Build library
        shell: cmd
        working-directory: ${{ github.workspace }}/libplacebo
        run: |
          mkdir build
          mkdir c:/libplacebo
          meson setup ${{ github.workspace }}/libplacebo/build
          meson configure ${{ github.workspace }}/libplacebo/build -Dd3d11=disabled -Ddemos=true -Dglslang=disabled -Dlcms=disabled -Dopengl=enabled -Dshaderc=disabled -Dunwind=disabled -Dvulkan=disabled -DUSE_GL -Dprefix=c:/libplacebo
          ninja -C${{ github.workspace }}/libplacebo/build
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: ${{github.workspace}}/libplacebo/build
          if-no-files-found: ignore
          retention-days: 0
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact-C
          path: c:/libplacebo
          if-no-files-found: ignore
          retention-days: 0
