name: Windows Build Meson

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install Python Dependencies
        run: pip install meson ninja
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: ${{github.workspace}}/upload
          if-no-files-found: ignore
          retention-days: 0
