name: Windows Build Meson

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Win:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Install Python Dependencies
        run: pip install meson ninja

      - name: Download sources
        shell: cmd
        run: |
          git clone --recursive https://github.com/haasn/libplacebo

      - name: Build library
        shell: cmd
        working-directory: ${{ github.workspace }}/libplacebo
        run: |
          mkdir build
          DIR=./build
          meson $DIR
          meson configure $DIR
        
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-artifact
          path: ${{github.workspace}}/upload
          if-no-files-found: ignore
          retention-days: 0
